config/routes.rb
Rails.application.routes.draw do
  resources :issues

  get 'list' => 'application#list'

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_attached_file :photo, :styles => { :medium => "614x614>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  USERS = { "admin" => Rails.configuration.admin_password }

  def list
    @issues = Issue.all
  end;

  private
      def authenticate
        authenticate_or_request_with_http_digest do |username|
          loggin = USERS[username]
          if !loggin.nil?
            session[:is_logged_in] = true;
          end
          loggin
        end
      end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate, except: [ :show ]
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:description, :location, :posted_date, :photo, :lat, :long)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/application/list.html.erb
<div class="pure-u-1">
    <h1>Listing issues</h1>

    <table>
      <thead>
        <tr>
          <th>#</th>
          <th>Description</th>
          <th>Location</th>
        </tr>
      </thead>

      <tbody>
        <% @issues.each do |issue| %>
          <tr>
            <td><%= link_to 'Show', issue %></td>
            <td><%= issue.description %></td>
            <td><%= issue.location %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
</div>

app/views/issues/_form.html.erb
<%= form_for( @issue, :html => { :multipart => true } ) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="field">
      <p>Lat</p> <%= f.text_area :lat %>
      <p>Long</p> <%= f.text_area :long %>
  </div>
  <div class="field">
    <%= f.file_field :photo %>
  </div>
 <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<div class="pure-u-1">
    <h1>Listing issues</h1>

    <table>
      <thead>
        <tr>
          <th>Description</th>
          <th>Location</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @issues.each do |issue| %>
          <tr>
            <td><%= issue.description %></td>
            <td><%= issue.location %></td>
            <td><%= link_to 'Show', issue %></td>
            <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
            <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Issue', new_issue_path %>
</div>

app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<div class="pure-u-1">
    <p id="notice"><%= notice %></p>
    <% if session[:is_logged_in] %>
        <%= link_to 'Back', '/issues' %>
    <% end %>
</div>

<div class="pure-u-3-5">
    <%= image_tag(
            @issue.photo.url(:medium),
            :class=> "issue__thumbnail"
        )
    %>
</div>
<div class="pure-u-2-5 box--padding issue__content">
    <p>
        <span>
            <a href="https://www.google.co.th/maps/?q=<%= @issue.lat %>,<%= @issue.long %>">
                <i class="fa fa-map-marker"></i>
                <%= @issue.location %>
            </a>
        </span>
    </p>
    <p>
        <%= @issue.description %>
    </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Betterbangkok</title>
  <link rel="stylesheet" href="//yui.yahooapis.com/pure/0.5.0/pure-min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal">
        <a class="pure-menu-heading" href="">BetterBangkok</a>
        <ul>
            <li><a href="#">เกี่ยวกับเรา</a></li>
        </ul>
    </div>

    <div class="content pure-g">
        <%= yield %>
    </div>

    <div class="footer pure-g">
        <div class="pure-u-1">
            <p>
                <a href="https://www.facebook.com/BetterBangkok"><i class="fa fa-facebook-square"></i></a>
                <a href="https://github.com/codeforthailand/BetterBangkok"><i class="fa fa-github-square"></i></a>
            </p>
        </div>

    </div>

</body>
</html>